- name: Create Job templates and dependencies for all palybooks in this repository in Controller
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    git_repo_url: "https://github.com/mglantz/controller-as-code"
    project_name: "{{ git_repo_url.split('/')[-1] }}"
    organization_name: "Default"
    inventory_name: "Demo Inventory"
    credentials_name: "Demo Credential"
    labels: "{{ project_name }}"
  tasks:
  - name: "Clone from git"
    ansible.builtin.git:
      repo: "{{ git_repo_url }}"
      dest: "~/checkout/{{ project_name }}"

  - name: "Create project"
    awx.awx.project:
      name: "{{ project_name }}"
      organization: "{{ organization_name  }}"
      state: present
      scm_type: git
      scm_url: "{{ git_repo_url }}"
      scm_branch: main
      scm_clean: yes
      scm_update_on_launch: no 

  - name: "Add job templates"
    awx.awx.job_template:
      name: "{{ item | replace('_',' ') }}"
      job_type: run
      organization: "{{ organization_name }}"
      inventory: "{{ inventory_name }}"
      project: "{{ project_name }}"
      playbook: "playbooks/{{ item }}.yml"
      credentials:
        - "{{ credentials_name }}"
      state: "present"
      allow_simultaneous: yes
      labels: "{{ labels }}"
      survey_enabled: yes
      survey_spec: "{{ lookup('file', 'playbooks/surveys/' + item + '.json') }}"
    vars_file:
      - "{{ lookup('file', '~/checkout/' + project_name + '/' + item + '_vars.yml' }}"
    loop: "{{ lookup('file', 'controller/job_templates.txt').splitlines() }}"

